title: "The Hideous One"
description: "Hi, This THO (The Hideous One). Here I write about stuff around me. Usually its about the game called Wuthering Waves but I also want to try new things too."
logo: "/assets/img/logo.png"
show_downloads: false
theme: minima
remote_theme: pages-themes/minimal
repository: "Atovenish/THO.github.io"
url: "https://THO.github.io"
baseurl: ""
